config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :delars
    resources :mobiles

    root to: "users#index"
  end

  get 'mobile/:mobile_id/:mobile_name' => 'home#mobile_show', :as => :view_mobile
  devise_for :users
  get 'home/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/delar.rb
class Delar < ApplicationRecord
	has_and_belongs_to_many :mobiles, :join_table => 'mobiles_delars'
end

app/models/mobile.rb
class Mobile < ApplicationRecord
	has_and_belongs_to_many :delars, :join_table => 'mobiles_delars'
	has_attached_file :image, styles: { medium: "800x300>", thumb: "3200x150>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_admin

    def authenticate_admin
      # TODO Add authentication logic here.
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/delars_controller.rb
module Admin
  class DelarsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Delar.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Delar.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/mobiles_controller.rb
module Admin
  class MobilesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Mobile.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Mobile.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@slider_mobiles = Mobile.limit(3)
  	if params['delar_city'].present?
      delars = Delar.where(:city => params['delar_city'])
    end
  	if request.xhr?
  		@mobiles = if params['mobile'].present?
	                  if delars.present?
	                    Mobile.joins(:mobiles_delars).where(mobile_params).where(["mobiles_delars.delar_id IN (?)", delars.map(&:id)]).uniq
	                  else
	                    Mobile.where(mobile_params).uniq
	                  end
               	   else
	  				   if delars.present?
	                     Mobile.joins(:mobiles_delars).where(["mobiles_delars.delar_id IN (?)", delars.map(&:id)]).uniq
	                   else
	                     Mobile.all.uniq
	                   end
	               end    
        render :partial => 'home/thumb_mobile', :collection => @mobiles,  :as => :mobile, :layout => false           
  	else	
  		@mobiles = Mobile.all
  	end	
  end

  def mobile_show
  	@mobile = Mobile.find(params[:mobile_id])
  end	

  private

  def mobile_params
  	params.require(:mobile).permit({:brand_name => []}, {:mobile_type => []}, {:battery_capacity => []}, {:screen_size => []},
                                   {:ram => []}, {:sim_type => []}, {:primary_camera => []}, {:os_version_name => []}, {:secondary_camera => []},
                                   {:features => []}, {:number_of_cores => []})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/fields/paperclip_field/_form.html.erb
<div class="field-unit__label">
  <%= f.label field.attribute %>
</div>
<div class="field-unit__field">
  <%= f.file_field field.attribute %>
</div>

app/views/fields/paperclip_field/_index.html.erb
<%= image_tag field.thumbnail %>

app/views/fields/paperclip_field/_show.html.erb
<%= image_tag field.thumbnail %>

app/views/home/_thumb_mobile.html.erb
<div class="col-sm-4 col-lg-4 col-md-4">
  <div class="thumbnail">
    <%= link_to image_tag(mobile.image.url(:thumb)), view_mobile_path(mobile.id, mobile.mobile_name) %>
    <div class="caption">
      <h4 class="pull-right">Rs.<%= mobile.price %></h4>
      <h4><a href="<%= view_mobile_path(mobile.id, mobile.mobile_name) %>" class="caption-title"><%= mobile.mobile_name %></a>
      </h4>
    </div>
  </div>
</div>

app/views/home/index.html.erb
hello nagaraju    <!-- Page Content -->
    <div class="container">

        <div class="row">
            <form id="filter">
                <div class="col-md-3">
                    <p class="lead">Shop Name</p>
                    <br/>
                    <br/>
                    <h4>Delars City</h4>
                      <div class="list-group">
                        <% Delar.all.map(&:city).select{|c| c.present?}.uniq.compact.each do |city| %>
                            <li class="list-group-item">
                              <input type="checkbox" name="delar_city[]" value="<%= city %>"> <span><%= city %></span>
                            </li>
                        <% end %>
                      </div>
                      <h4>BRAND</h4>
            <div class="list-group">
              <% @mobiles.map(&:brand_name).select{|c| c.present?}.uniq.compact.each do |brand_name| %>
                  <li class="list-group-item">
                    <input type="checkbox" name="mobile[brand_name][]" value="<%= brand_name %>"> <span><%= brand_name %></span>
                  </li>
              <% end %>
            </div>

          <h4>MOBILE TYPE</h4>
          <div class="list-group">
            <% @mobiles.map(&:mobile_type).select{|c| c.present?}.uniq.compact.each do |mobile_type| %>
                <li class="list-group-item">
                  <input type="checkbox" name="mobile[mobile_type][]" value="<%= mobile_type %>"> <span><%= mobile_type %></span>
                </li>
            <% end %>
          </div>

          <h4>BATTERY CAPACITY</h4>
          <div class="list-group">
            <% @mobiles.map(&:battery_capacity).select{|c| c.present?}.uniq.compact.each do |battery_capacity| %>
                <li class="list-group-item">
                  <input type="checkbox" name="mobile[battery_capacity][]" value="<%= battery_capacity %>"> <span><%= battery_capacity %></span>
                </li>
            <% end %>
          </div>

          <h4>SCREEN SIZE</h4>
          <div class="list-group">
            <% @mobiles.map(&:screen_size).select{|c| c.present?}.uniq.compact.each do |screen_size| %>
                <li class="list-group-item">
                  <input type="checkbox" name="mobile[screen_size][]" value="<%= screen_size %>"> <span><%= screen_size %></span>
                </li>
            <% end %>
          </div>

          <h4>RAM</h4>
          <div class="list-group">
            <% @mobiles.map(&:ram).select{|c| c.present?}.uniq.compact.each do |ram| %>
                <li class="list-group-item">
                  <input type="checkbox" name="mobile[ram][]" value="<%= ram %>"> <span><%= ram %></span>
                </li>
            <% end %>
          </div>

          <h4>SIM TYPE</h4>
          <div class="list-group">
            <% @mobiles.map(&:sim_type).select{|c| c.present?}.uniq.compact.each do |sim_type| %>
                <li class="list-group-item">
                  <input type="checkbox" name="mobile[sim_type][]" value="<%= sim_type %>"> <span><%= sim_type %></span>
                </li>
            <% end %>
          </div>

          <h4>PRIMARY CAMERA</h4>
          <div class="list-group">
            <% @mobiles.map(&:primary_camera).select{|c| c.present?}.uniq.compact.each do |primary_camera| %>
                <li class="list-group-item">
                  <input type="checkbox" name="mobile[primary_camera][]" value="<%= primary_camera %>"> <span><%= primary_camera %></span>
                </li>
            <% end %>
          </div>

          <h4>OS VERSION NAME</h4>
          <div class="list-group">
            <% @mobiles.map(&:os_version_name).select{|c| c.present?}.uniq.compact.each do |os_version_name| %>
                <li class="list-group-item">
                  <input type="checkbox" name="mobile[os_version_name][]" value="<%= os_version_name %>"> <span><%= os_version_name %></span>
                </li>
            <% end %>
          </div>

          <h4>SECONDARY CAMERA</h4>
          <div class="list-group">
            <% @mobiles.map(&:secondary_camera).select{|c| c.present?}.uniq.compact.each do |secondary_camera| %>
                <li class="list-group-item">
                  <input type="checkbox" name="mobile[secondary_camera][]" value="<%= secondary_camera %>"> <span><%= secondary_camera %></span>
                </li>
            <% end %>
          </div>

          <h4>FEATURES</h4>
          <div class="list-group">
            <% @mobiles.map(&:features).select{|c| c.present?}.uniq.compact.each do |features| %>
                <li class="list-group-item">
                  <input type="checkbox" name="mobile[features][]" value="<%= features %>"> <span><%= features %></span>
                </li>
            <% end %>
          </div>

          <h4>NUMBER OF CORES</h4>
          <div class="list-group">
            <% @mobiles.map(&:number_of_cores).select{|c| c.present?}.uniq.each do |number_of_cores| %>
                <li class="list-group-item">
                  <input type="checkbox" name="mobile[number_of_cores][]" value="<%= number_of_cores %>"> <span><%= number_of_cores %></span>
                </li>
            <% end %>
          </div>  
                </div>
            </form>

            <div class="col-md-9">

                <div class="row carousel-holder">

                    <div class="col-md-12">
                        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                            </ol>
                            <div class="carousel-inner">
                            <% @slider_mobiles.each_with_index do |mobile, i| %>
                                <div class="item <%= 'active' if i == 0 %>">
                                     <%= link_to image_tag(mobile.image.url(:medium)), view_mobile_path(mobile.id, mobile.mobile_name) %>
                                </div>
                            <% end %>
                            </div>
                            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left"></span>
                            </a>
                            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right"></span>
                            </a>
                        </div>
                    </div>

                </div>

                <div class="row" id="thumb-mobile">
                    <% @mobiles.each do |mobile| %>
                        <div class="col-sm-4 col-lg-4 col-md-4">
                            <div class="thumbnail">
                                <%= link_to image_tag(mobile.image.url(:thumb)), view_mobile_path(mobile.id, mobile.mobile_name) %>
                                <div class="caption">
                                    <h4 class="pull-right">Rs.<%= mobile.price %></h4>
      <h4><a href="<%= view_mobile_path(mobile.id, mobile.mobile_name) %>" class="caption-title"><%= mobile.mobile_name %></a>
                                </div>                               
                            </div>
                        </div>
                    <% end %>

                </div>

            </div>

        </div>

    </div>
    <!-- /.container -->

    <div class="container">

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2017</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->

<script type="text/javascript">
  $('form input').on('change', function(){
      var data = $('form').serialize();
      $.ajax({
          url: '/',
          data: data,
          processData: false,
          type: 'GET',
          success: function ( data ) {
              console.log(data);
              $('#thumb-mobile').html(data);
          }
      });
  });
</script>

app/views/home/mobile_show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4" style="padding-top: 50px;">
      <%= image_tag @mobile.image.url(:medium) %>
    </div>
    <div class="col-md-4">
      <h3><%= @mobile.mobile_name %></h3>
      <dl class="dl-horizontal">
        <% skip_values = ['id', 'mobile_name', 'created_at', 'updated_at', 'image_file_name', 'image_content_type', 'image_file_size', 'image_updated_at']%>
        <% @mobile.attributes.each do |title, value|%>
          <% unless skip_values.include?(title) %>
            <dt><%= title.gsub('_', ' ').capitalize %></dt>
            <dd><%= 'Rs. ' if title == 'price' %><%= value %></dd>
          <% end %>
        <% end %>
      </dl>
    </div>
  </div>
  <div class="row">
      <h4>Delars:</h4>
      <% @mobile.delars.each do |delar| %>
        <div class="col-md-4">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title"><%= delar.name %></h3>
            </div>
            <% skip_values = ['id', 'name', 'address', 'created_at', 'updated_at']%>
            <div class="panel-body">
              <dl class="dl-horizontal" >
                <% delar.attributes.each do |title, value|%>
                    <% unless skip_values.include?(title) %>
                        <dt><%= title.gsub('_', ' ').capitalize %></dt>
                        <dd><%= value %></dd>
                    <% end %>
                <% end %>
              </dl>
            </div>            
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
      <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Home</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <%= link_to 'About', page_path('about') %>
                    </li>
                    <li>
                        <a href="/users/sign_in">Login</a>
                    </li>
                    <li>
                        <a href="/users/sign_up">Register</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnlineMobileSales</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <%= render :partial => 'layouts/navigation' %>    
  </header>
    <main role="main">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
    <div class="row">
      <div class="col-md-4">
        <img src="/assets/about.jpeg" width="100%" />
      </div>
      <div class="col-md-8">
        <% content_for :title do %>About<% end %>
        <h3>About the Website</h3>
        <p>
          The main use of this website is the customer can easily search details of the

          mobile in which customer is willing to buy he can do all this from home by

          registering to the online mobile services, he gets email alerts on special occasions

          regarding offers, so that it will be easy to the customer to buy.
        </p>
      </div>
    </div>
</div>